services:
    frontend:
        build: ./frontend
        working_dir: /app
        volumes:
            - ./frontend:/app
        ports:
            - '3000:3000'
        command: sh -c "npm install && npm start"
        depends_on:
            - backend
        networks:
            - app-network

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        expose:
            - '5000'
        environment:
            MONGO_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/${MONGO_DATABASE}
        depends_on:
            - mongo
        networks:
            - app-network

    mongo:
        image: mongo:latest
        volumes:
            - mongo-data:/data/db
        expose:
            - '27017'
        environment:
            MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        expose:
            - '80'
        depends_on:
            - frontend
            - backend
        networks:
            - app-network

    modsecurity:
        image: owasp/modsecurity-crs:4.7.0-nginx-202410090410
        container_name: app-modsecurity
        depends_on:
            - backend
        ports:
            - '80:8080'
            - 443:8443
        environment:
            - BACKEND=http://nginx:80
            - PORT=8080
            - BACKEND_SSL=false
            - SSL=on
            - PROXY_SSL_VERIFY=off
            - MODSEC_RULE_ENGINE=On
            # Add these audit settings
            - MODSEC_AUDIT_ENGINE=On
            - MODSEC_AUDIT_LOG_FORMAT=JSON
            - MODSEC_AUDIT_LOG=/var/log/modsec_audit.log
            - MODSEC_AUDIT_LOG_TYPE=Serial
            - MODSEC_AUDIT_STORAGE=/var/log/modsec_audit
            - MODSEC_INBOUND_ANOMALY_SCORE_THRESHOLD=2
            - PARANOIA=1
            - MODSEC_BLOCKING_PARANOIA=1
        volumes:
            - ./modsecurity-override.conf:/etc/nginx/templates/modsecurity.d/modsecurity-override.conf.template
        networks:
            - app-network

volumes:
    mongo-data:
    modsec_data:

networks:
    app-network:
