version: '3'
services:
    frontend:
        build: ./frontend
        working_dir: /app
        volumes:
            - ./frontend:/app
        expose:
            - '3000'
        command: sh -c "npm install && npm start"
        depends_on:
            - backend
        networks:
            app-network:

    backend:
        build: ./backend
        working_dir: /app
        volumes:
            - ./backend:/app
        expose:
            - '5000'
        command: sh -c "npm install && npm run build && npm start"
        environment:
            MONGO_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/${MONGO_DATABASE}
        depends_on:
            - mongo
        networks:
            app-network:

    mongo:
        image: mongo:latest
        volumes:
            - mongo-data:/data/db
        expose:
            - '27017'
        environment:
            MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        networks:
            app-network:

    security:
        build: ./security
        ports:
            - '80:80'
        depends_on:
            - frontend
        networks:
            app-network:

volumes:
    mongo-data:

networks:
    app-network:
