version: '3'
services:
    frontend:
        build: ./frontend
        working_dir: /app
        volumes:
            - ./frontend:/app
        ports:
            - '3000:3000'
        command: sh -c "npm install && npm start"
        depends_on:
            - backend

    backend:
        build: ./backend
        working_dir: /app
        volumes:
            - ./backend:/app
        ports:
            - '5001:5000'
        command: sh -c "npm install && npm run build && npm start"
        environment:
            MONGO_URL: mongodb://mongo:27017/mydatabase
        depends_on:
            - mongo

    mongo:
        image: mongo:latest
        volumes:
            - mongo-data:/data/db
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_DATABASE: reactcalendar_db

volumes:
    mongo-data:
